// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIH5OG5y_EL-sp1yGjOxiom5A654n4tn8',
    appId: '1:152179311533:web:29767b720127ce9fbd9724',
    messagingSenderId: '152179311533',
    projectId: 'moajo-app',
    authDomain: 'moajo-app.firebaseapp.com',
    storageBucket: 'moajo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdxL4T_kFatrnqMRYI_x1SWmt8u7cMt4',
    appId: '1:152179311533:android:e6856bf7b5fce25fbd9724',
    messagingSenderId: '152179311533',
    projectId: 'moajo-app',
    storageBucket: 'moajo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsq95a2Ojsu4fSIscBGTjh0GuaVeAMuc',
    appId: '1:152179311533:ios:4c146eb442cad70dbd9724',
    messagingSenderId: '152179311533',
    projectId: 'moajo-app',
    storageBucket: 'moajo-app.appspot.com',
    androidClientId: '152179311533-23ktj1fi7u3fpb2dcie1p2u439dng99a.apps.googleusercontent.com',
    iosClientId: '152179311533-2lsvtrj7junkos93nd2oekpropcv8929.apps.googleusercontent.com',
    iosBundleId: 'com.beside.moa',
  );
}
